Resources:
  ChannelTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.channelTableName}
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.linkTableName}
      AttributeDefinitions:
        - AttributeName: linkId
          AttributeType: S
        - AttributeName: linkTimestamp
          AttributeType: S
        - AttributeName: writerName
          AttributeType: S
        - AttributeName: channelName
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
        - AttributeName: linkTimestamp
          KeyType: RANGE

      LocalSecondaryIndexes:
        - IndexName: userIndex
          KeySchema:
            - AttributeName: url
              KeyType: HASH
            - AttributeName: userName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: channelIndex
          KeySchema:
            - AttributeName: url
              KeyType: HASH
            - AttributeName: channelName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
