service:
  name: codesquad-link-archive
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
    excludeFiles: src/**/*.test.js

  channelTableName: ${opt:stage, 'dev'}-channels
  userTableName: ${opt:stage, 'dev'}-users
  linkTableName: ${opt:stage, 'dev'}-links

  dynamodb:
    stages:
      - dev
      - test
    start:
      port: 8000
      inMemory: true
      migrate: true
      sharedDb: true

plugins:
  - serverless-jest-plugin
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:REGION}
  state: ${opt:stage, 'dev'}
  memorySize: 128
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

package:
  individually: true

functions:
  crawler:
    handler: src/crawler/index.crawl
    timeout: 20
    events:
      - schedule:
          rate: cron(0 4 * * ? *)

resources:
  - ${file(resources/dynamodb-table.yml)}
