Resources:
  ChannelTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.channelTableName}
      AttributeDefinitions:
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 3

  LinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.linkTableName}
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
        - AttributeName: linkTimestamp
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: channelId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
        - AttributeName: linkTimestamp
          KeyType: RANGE

      GlobalSecondaryIndexes:
#        - IndexName: UserTimestampIndex
#          KeySchema:
#            - AttributeName: userId
#              KeyType: HASH
#            - AttributeName: linkTimestamp
#              KeyType: RANGE
#          Projection:
#            ProjectionType: ALL
#          ProvisionedThroughput:
#            ReadCapacityUnits: 5
#            WriteCapacityUnits: 5
#        - IndexName: ChannelTimestampIndex
#          KeySchema:
#            - AttributeName: channelId
#              KeyType: HASH
#            - AttributeName: linkTimestamp
#              KeyType: RANGE
#          Projection:
#            ProjectionType: ALL
#          ProvisionedThroughput:
#            ReadCapacityUnits: 5
#            WriteCapacityUnits: 5
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: date
              KeyType: HASH
            - AttributeName: linkTimestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

      LocalSecondaryIndexes:
        - IndexName: userIndex
          KeySchema:
            - AttributeName: url
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: channelIndex
          KeySchema:
            - AttributeName: url
              KeyType: HASH
            - AttributeName: channelId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
