Resources:
  CrawlerFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:custom.cralwerFailureTopicName}
      DisplayName: Crawler occurred failure!
      Subscription:
        - Protocol: email
          Endpoint: ${self:custom.cralwerFailureEndpoint}
