name: Deploy projects

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy to release(master) branch
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'cd skip')"

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn

      - name: Install Serverless CLI
        run: |
          npm i -g serverless

      - name: Deploy lambda functions
        run: |
          yarn deploy
        env:
          STAGE: 'prod'
