name: Node.js CI

on:
  pull_request:
    branches: 
      - master

jobs:
  ci:
    name: Test and build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.0
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        yarn
        
    - run: yarn test

    - name: Install serverless CLI
      run: |
        npm i -g serverless@1.65.0

    - name: Build test
      run: |
        yarn build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
